default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: portgram_development

test:
  <<: *default
  database: portgram_test

production:
  <<: *default
  database: portgram_production
  username: portgram
  password: